version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend.Dockerfile
    ports:
      - 3030:3030
    # env_file: /f.env
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend.Dockerfile
    ports: 
      - 8080:8080
    env_file: ./backend/.env